/* The following code was generated by JFlex 1.4.1 on 6/19/11 4:41 PM */

/*******************************************************************************
 * Copyright (c) 2006 Zend Corporation and IBM Corporation.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   Zend and IBM - Initial implementation
 *******************************************************************************/

package org.eclipse.twig.core.ast.scanner;

import java.io.IOException;
import java.util.LinkedList;
import java.util.List;

import org.eclipse.php.internal.core.ast.nodes.IDocumentorLexer;
import org.eclipse.php.internal.core.ast.nodes.Comment;
import java_cup.sym;
import org.eclipse.php.internal.core.ast.nodes.AST;
import java_cup.runtime.Symbol;
import org.eclipse.php.internal.core.ast.scanner.StateStack;
import org.eclipse.twig.core.util.Debug;
import org.eclipse.wst.sse.core.utils.StringUtils;




/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.1
 * on 6/19/11 4:41 PM from the specification file
 * <tt>ast_scanner.flex</tt>
 */
public class TwigAstLexer implements AstLexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int ST_LOOKING_FOR_PROPERTY = 5;
  public static final int ST_IN_SCRIPTING = 1;
  public static final int ST_LOOKING_FOR_VARNAME = 6;
  public static final int ST_DOUBLE_QUOTES = 3;
  public static final int YYINITIAL = 0;
  public static final int ST_BACKQUOTE = 4;
  public static final int ST_IN_PRINTING = 2;

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\12\1\11\2\0\1\13\22\0\1\12\1\37\1\15\1\0"+
    "\1\14\1\44\1\45\1\64\1\55\1\56\1\42\1\35\1\52\1\4"+
    "\1\2\1\43\1\5\11\1\1\51\1\50\1\40\1\36\1\41\1\60"+
    "\1\61\1\31\1\7\1\33\1\26\1\3\1\22\2\10\1\21\2\10"+
    "\1\23\1\10\1\25\1\27\2\10\1\30\1\24\1\32\1\34\1\63"+
    "\1\10\1\6\2\10\1\53\1\16\1\54\1\47\1\10\1\17\1\31"+
    "\1\7\1\33\1\26\1\3\1\22\2\10\1\21\2\10\1\23\1\10"+
    "\1\25\1\27\2\10\1\30\1\24\1\32\1\34\1\63\1\10\1\6"+
    "\2\10\1\20\1\46\1\62\1\57\201\10\uff00\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\7\0\2\1\1\2\1\3\1\4\1\5\1\2\3\4"+
    "\1\6\1\7\1\10\1\11\1\12\5\4\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\1\1\41\1\42\1\4"+
    "\1\1\1\43\2\1\1\42\1\4\2\1\1\44\1\1"+
    "\1\45\1\46\1\47\1\50\1\51\1\0\1\52\1\0"+
    "\1\53\3\4\1\54\1\55\1\0\1\4\3\0\1\56"+
    "\2\0\1\57\2\4\1\60\1\61\2\4\1\62\1\63"+
    "\1\64\1\65\1\66\1\67\1\70\1\71\1\72\1\73"+
    "\1\0\1\74\1\75\1\76\1\77\1\100\1\101\1\102"+
    "\4\0\1\42\2\103\1\104\1\103\3\0\1\42\3\105"+
    "\2\106\1\52\1\0\3\4\1\52\1\107\1\4\1\110"+
    "\1\111\1\112\1\113\1\114\3\0\2\102\2\115\1\4"+
    "\1\116\3\4\1\117\1\0\2\4\1\120\2\4\1\0"+
    "\1\4\1\121\1\122\1\4\1\0\1\123\1\124\10\0"+
    "\1\125";

  private static int [] zzUnpackAction() {
    int [] result = new int[177];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\237\0\324\0\u0109\0\u013e\0\u0173"+
    "\0\u01a8\0\u01dd\0\u0212\0\u0247\0\u027c\0\u02b1\0\u02e6\0\u031b"+
    "\0\u0350\0\u0385\0\u0173\0\u03ba\0\u0173\0\u0173\0\u03ef\0\u0424"+
    "\0\u0459\0\u048e\0\u04c3\0\u04f8\0\u052d\0\u0562\0\u0597\0\u05cc"+
    "\0\u0601\0\u0636\0\u066b\0\u06a0\0\u06d5\0\u070a\0\u0173\0\u0173"+
    "\0\u0173\0\u0173\0\u0173\0\u0173\0\u0173\0\u0173\0\u0173\0\u0173"+
    "\0\u073f\0\u0774\0\u0173\0\u07a9\0\u07de\0\u0813\0\u0173\0\u0848"+
    "\0\u087d\0\u08b2\0\u08e7\0\u091c\0\u0951\0\u0173\0\u0986\0\u0173"+
    "\0\u0173\0\u09bb\0\u0173\0\u09f0\0\u0a25\0\u0a5a\0\u0a8f\0\u0173"+
    "\0\u0ac4\0\u0af9\0\u0b2e\0\u0173\0\u0173\0\u0b63\0\u0b98\0\u0774"+
    "\0\u03ba\0\u0bcd\0\u0173\0\u0c02\0\u0c37\0\u0350\0\u0c6c\0\u0ca1"+
    "\0\u0350\0\u0350\0\u0cd6\0\u0d0b\0\u0173\0\u0173\0\u0173\0\u0173"+
    "\0\u0173\0\u0d40\0\u0173\0\u0d75\0\u0173\0\u0173\0\u0daa\0\u0173"+
    "\0\u0173\0\u0173\0\u0173\0\u0173\0\u0173\0\u0ddf\0\u0e14\0\u0813"+
    "\0\u0848\0\u0e49\0\u0e7e\0\u0813\0\u0173\0\u0173\0\u0e49\0\u091c"+
    "\0\u0951\0\u0eb3\0\u0ee8\0\u091c\0\u0173\0\u0eb3\0\u0173\0\u0f1d"+
    "\0\u0f52\0\u0f52\0\u0f87\0\u0fbc\0\u0ff1\0\u0b63\0\u0350\0\u1026"+
    "\0\u0350\0\u0350\0\u0350\0\u0173\0\u0173\0\u105b\0\u1090\0\u10c5"+
    "\0\u0173\0\u10fa\0\u07a9\0\u08b2\0\u112f\0\u1164\0\u1199\0\u11ce"+
    "\0\u1203\0\u0173\0\u1238\0\u126d\0\u12a2\0\u0350\0\u12d7\0\u130c"+
    "\0\u1341\0\u1376\0\u0350\0\u0350\0\u13ab\0\u13e0\0\u0350\0\u0350"+
    "\0\u1415\0\u144a\0\u147f\0\u14b4\0\u14e9\0\u151e\0\u1553\0\u1588"+
    "\0\u0173";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[177];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\20\10\1\11\45\10\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\3\22\1\23\1\24\1\10\1\25"+
    "\1\26\1\27\1\30\4\21\1\31\1\21\1\32\2\21"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\1\51\1\52"+
    "\1\53\1\54\1\55\1\56\1\57\1\60\1\61\1\21"+
    "\1\62\65\63\3\64\1\65\2\64\3\65\3\64\1\66"+
    "\1\67\1\70\1\64\1\71\14\65\26\64\1\65\1\64"+
    "\3\72\1\73\2\72\3\73\3\72\1\74\1\72\1\75"+
    "\1\76\1\77\14\73\26\72\1\73\1\72\2\100\1\101"+
    "\1\102\2\100\3\102\3\22\5\100\14\102\26\100\1\102"+
    "\1\100\3\103\1\104\2\103\3\104\10\103\14\104\26\103"+
    "\1\104\1\103\105\0\1\105\45\0\1\12\1\106\1\107"+
    "\1\0\1\12\60\0\1\106\3\0\1\106\30\0\1\110"+
    "\27\0\1\21\1\0\1\21\1\0\1\21\1\111\2\21"+
    "\10\0\2\21\1\112\1\21\1\113\7\21\26\0\1\21"+
    "\5\0\1\114\31\0\1\115\27\0\1\12\1\106\1\107"+
    "\1\0\1\12\1\116\57\0\1\21\1\0\1\21\1\0"+
    "\4\21\10\0\6\21\1\117\5\21\26\0\1\21\2\0"+
    "\1\21\1\0\1\21\1\0\4\21\4\0\1\24\3\0"+
    "\14\21\26\0\1\21\1\120\1\0\1\21\1\0\1\21"+
    "\1\0\4\21\10\0\14\21\26\0\1\21\12\0\3\22"+
    "\51\0\14\121\1\122\1\123\1\124\1\121\1\125\44\121"+
    "\1\0\1\21\1\0\1\21\1\0\4\21\10\0\1\21"+
    "\1\126\2\21\1\127\7\21\26\0\1\21\2\0\1\21"+
    "\1\0\1\21\1\0\4\21\10\0\6\21\1\130\5\21"+
    "\26\0\1\21\2\0\1\21\1\0\1\21\1\0\4\21"+
    "\10\0\7\21\1\131\4\21\26\0\1\21\2\0\1\21"+
    "\1\0\1\21\1\0\4\21\10\0\3\21\1\132\1\133"+
    "\7\21\26\0\1\21\2\0\1\21\1\0\1\21\1\0"+
    "\4\21\10\0\3\21\1\134\10\21\26\0\1\21\36\0"+
    "\1\135\1\136\64\0\1\137\64\0\1\140\64\0\1\141"+
    "\1\0\1\142\1\140\61\0\1\143\2\0\1\144\61\0"+
    "\1\145\64\0\1\146\3\0\1\147\60\0\1\150\64\0"+
    "\1\151\6\0\1\152\55\0\1\153\7\0\1\154\54\0"+
    "\1\155\110\0\1\156\2\0\16\120\1\157\45\120\1\123"+
    "\14\64\1\160\1\0\1\161\1\64\1\162\45\64\1\65"+
    "\1\163\1\65\1\64\4\65\3\64\1\160\1\0\1\161"+
    "\1\64\1\162\14\65\26\64\1\65\4\64\1\0\2\64"+
    "\3\0\3\64\1\164\1\165\1\161\1\64\15\0\26\64"+
    "\1\0\102\64\1\166\1\165\1\161\1\64\1\167\44\64"+
    "\14\72\1\170\1\72\1\171\1\0\1\172\45\72\1\73"+
    "\1\173\1\73\1\72\4\73\3\72\1\170\1\72\1\171"+
    "\1\0\1\172\14\73\26\72\1\73\4\72\1\0\2\72"+
    "\3\0\3\72\1\174\1\72\1\171\1\175\15\0\26\72"+
    "\1\0\102\72\1\166\1\72\1\171\1\175\1\176\44\72"+
    "\1\0\1\102\1\0\1\102\1\0\4\102\10\0\14\102"+
    "\26\0\1\102\2\0\1\104\1\0\1\104\1\0\4\104"+
    "\10\0\14\104\26\0\1\104\12\0\2\177\1\200\52\0"+
    "\1\106\1\0\1\107\1\0\1\106\60\0\1\201\2\0"+
    "\1\202\1\201\27\0\1\202\30\0\1\21\1\0\1\21"+
    "\1\0\4\21\10\0\11\21\1\203\2\21\26\0\1\21"+
    "\2\0\1\21\1\0\1\21\1\0\4\21\10\0\3\21"+
    "\1\204\10\21\26\0\1\21\2\0\1\21\1\0\1\21"+
    "\1\0\4\21\10\0\5\21\1\205\6\21\26\0\1\21"+
    "\2\0\1\206\1\0\1\206\1\0\1\206\1\0\1\206"+
    "\12\0\1\206\3\0\1\206\2\0\1\206\1\0\1\206"+
    "\32\0\1\21\1\0\1\21\1\0\4\21\10\0\7\21"+
    "\1\207\4\21\26\0\1\21\1\0\3\121\1\0\2\121"+
    "\3\0\3\121\1\122\1\123\1\124\1\121\15\0\26\121"+
    "\1\0\102\121\1\0\1\123\1\124\1\121\1\125\44\121"+
    "\1\0\1\21\1\0\1\21\1\0\4\21\10\0\12\21"+
    "\1\210\1\21\26\0\1\21\2\0\1\21\1\0\1\21"+
    "\1\0\4\21\10\0\7\21\1\211\4\21\26\0\1\21"+
    "\2\0\1\21\1\0\1\21\1\0\4\21\10\0\5\21"+
    "\1\212\6\21\26\0\1\21\2\0\1\21\1\0\1\213"+
    "\1\0\4\21\10\0\14\21\26\0\1\21\37\0\1\214"+
    "\64\0\1\215\37\0\3\216\26\0\1\217\16\0\1\220"+
    "\14\0\1\221\1\0\1\222\51\0\65\120\14\64\1\0"+
    "\1\165\1\161\1\64\1\167\47\64\1\223\2\64\3\223"+
    "\3\64\1\160\1\0\1\161\1\64\1\162\14\223\26\64"+
    "\1\223\1\64\14\72\1\0\1\72\1\171\1\175\1\176"+
    "\47\72\1\224\2\72\3\224\3\72\1\170\1\72\1\171"+
    "\1\0\1\172\14\224\26\72\1\224\1\72\11\0\1\177"+
    "\54\0\1\201\3\0\1\201\60\0\1\21\1\0\1\225"+
    "\1\0\4\21\10\0\14\21\26\0\1\21\2\0\1\21"+
    "\1\0\1\226\1\0\4\21\10\0\14\21\26\0\1\21"+
    "\2\0\1\21\1\0\1\21\1\0\4\21\10\0\1\227"+
    "\1\230\12\21\26\0\1\21\2\0\1\21\1\0\1\21"+
    "\1\0\4\21\10\0\2\21\1\231\11\21\26\0\1\21"+
    "\12\0\3\216\45\0\1\220\46\0\1\232\104\0\1\233"+
    "\12\0\1\221\54\0\1\21\1\0\1\21\1\0\4\21"+
    "\10\0\4\21\1\234\7\21\26\0\1\21\2\0\1\21"+
    "\1\0\1\21\1\0\4\21\10\0\1\235\13\21\26\0"+
    "\1\21\2\0\1\21\1\0\1\21\1\0\4\21\10\0"+
    "\1\21\1\236\12\21\26\0\1\21\2\0\1\21\1\0"+
    "\1\21\1\0\4\21\10\0\6\21\1\237\5\21\26\0"+
    "\1\21\2\0\1\21\1\0\1\21\1\0\4\21\10\0"+
    "\13\21\1\240\26\0\1\21\32\0\1\241\34\0\1\21"+
    "\1\0\1\21\1\0\4\21\10\0\5\21\1\242\6\21"+
    "\26\0\1\21\2\0\1\21\1\0\1\21\1\0\4\21"+
    "\10\0\1\21\1\243\12\21\26\0\1\21\2\0\1\21"+
    "\1\0\1\21\1\0\4\21\10\0\7\21\1\244\4\21"+
    "\26\0\1\21\2\0\1\21\1\0\1\21\1\0\4\21"+
    "\10\0\5\21\1\245\6\21\26\0\1\21\31\0\1\246"+
    "\35\0\1\21\1\0\1\21\1\0\4\21\10\0\3\21"+
    "\1\247\10\21\26\0\1\21\2\0\1\21\1\0\1\250"+
    "\1\0\4\21\10\0\14\21\26\0\1\21\12\0\3\251"+
    "\54\0\1\252\2\0\3\252\3\251\1\253\4\0\14\252"+
    "\26\0\1\252\2\0\1\252\1\0\1\252\1\0\4\252"+
    "\3\254\5\0\14\252\26\0\1\252\4\0\1\252\2\0"+
    "\3\252\10\0\14\252\26\0\1\252\4\0\1\255\2\0"+
    "\3\255\3\254\2\0\1\256\2\0\14\255\5\0\1\257"+
    "\3\0\1\256\14\0\1\255\2\0\1\255\1\0\1\255"+
    "\1\0\4\255\3\260\2\0\1\256\2\0\14\255\5\0"+
    "\1\257\3\0\1\256\14\0\1\255\4\0\1\255\2\0"+
    "\3\255\3\260\2\0\1\256\2\0\14\255\5\0\1\257"+
    "\3\0\1\256\14\0\1\255\44\0\1\261\32\0\3\260"+
    "\26\0\1\257\22\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5565];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\7\0\1\11\12\1\1\11\1\1\2\11\20\1\12\11"+
    "\2\1\1\11\3\1\1\11\6\1\1\11\1\1\2\11"+
    "\1\1\1\11\1\1\1\0\1\1\1\0\1\11\3\1"+
    "\2\11\1\0\1\1\3\0\1\11\2\0\7\1\5\11"+
    "\1\1\1\11\1\1\2\11\1\0\6\11\1\1\4\0"+
    "\2\1\2\11\1\1\3\0\2\1\1\11\1\1\1\11"+
    "\2\1\1\0\11\1\2\11\3\0\1\11\10\1\1\11"+
    "\1\0\5\1\1\0\4\1\1\0\2\1\10\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[177];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
	private final LinkedList commentList = new LinkedList();
    private StateStack stack = new StateStack();
    private char yy_old_buffer[] = new char[ZZ_BUFFERSIZE];
    private int yy_old_pushbackPos;
    protected int commentStartPosition;

	private AST ast;

    public void setAST(AST ast) {
    	this.ast = ast;
    }
    
    
	public void setInScriptingState() {
		yybegin(ST_IN_SCRIPTING);
	}

	public void resetCommentList() {
		commentList.clear();
	}
	
	public LinkedList getCommentList() {
		return commentList;
	}	
	
	protected void addComment(int type) {
		int leftPosition = getTokenStartPosition();
		Comment comment = new Comment(commentStartPosition, leftPosition + getTokenLength(), ast, type);
		commentList.add(comment);
	}	
	
	
	
	
    private void pushState(int state) {
        stack.pushStack(zzLexicalState);
        yybegin(state);
    }

    private void popState() {
        yybegin(stack.popStack());
    }

    public int getCurrentLine() {
        return yyline;
    }

    protected int getTokenStartPosition() {
        return zzStartRead - zzPushbackPos;
    }

    protected int getTokenLength() {
        return zzMarkedPos - zzStartRead;
    }

    public int getLength() {
        return zzEndRead - zzPushbackPos;
    }
    
    private void handleCommentStart() {
		commentStartPosition = getTokenStartPosition();
	}
	
	private void handleLineCommentEnd() {
         addComment(Comment.TYPE_SINGLE_LINE);
    }
    
    private void handleMultilineCommentEnd() {
    	addComment(Comment.TYPE_MULTILINE);
    }

    private void handlePHPDocEnd() {
		addComment(Comment.TYPE_PHPDOC);
    }
    
    protected void handleVarComment() {
    	commentStartPosition = zzStartRead;
    	addComment(Comment.TYPE_MULTILINE);
    }
        
    private Symbol createFullSymbol(int symbolNumber) {
        Symbol symbol = createSymbol(symbolNumber);
        symbol.value = yytext();
        return symbol;
    }

    protected Symbol createSymbol(int symbolNumber) {
        int leftPosition = getTokenStartPosition();
        return new Symbol(symbolNumber, leftPosition, leftPosition + getTokenLength());
    }

    public int[] getParamenters(){
    	return new int[]{zzMarkedPos, zzPushbackPos, zzCurrentPos, zzStartRead, zzEndRead, yyline};
    }
    
	protected boolean parsePHPDoc(){	
		final IDocumentorLexer documentorLexer = getDocumentorLexer(zzReader);
		if(documentorLexer == null){
			return false;
		}
		yypushback(zzMarkedPos - zzStartRead);
		int[] parameters = getParamenters();
		documentorLexer.reset(zzReader, zzBuffer, parameters);
		Object phpDocBlock = documentorLexer.parse();
		commentList.add(phpDocBlock);
		reset(zzReader, documentorLexer.getBuffer(), documentorLexer.getParamenters());
		return true;
	}
	
	
	protected IDocumentorLexer getDocumentorLexer(java.io.Reader  reader) {
		return null;
	}
	
	public void reset(java.io.Reader  reader, char[] buffer, int[] parameters){
		this.zzReader = reader;
		this.zzBuffer = buffer;
		this.zzMarkedPos = parameters[0];
		this.zzPushbackPos = parameters[1];
		this.zzCurrentPos = parameters[2];
		this.zzStartRead = parameters[3];
		this.zzEndRead = parameters[4];
		this.yyline = parameters[5];  
		this.yychar = this.zzStartRead - this.zzPushbackPos;
	}
	
	private final void dump(String s) {
		if (Debug.debugLexer) {
			System.err.println(s + " (" + yychar + "-" + //$NON-NLS-2$//$NON-NLS-1$
				(yylength() + yychar) + "):\'" +//$NON-NLS-1$
					StringUtils.escape(yytext()) + "\'");//$NON-NLS-1$
		}
	}
	



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public TwigAstLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public TwigAstLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 174) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzPushbackPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead < 0) {
      return true;
    }
    else {
      zzEndRead+= numRead;
      return false;
    }
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = zzPushbackPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = zzLexicalState;


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 42: 
          { return createFullSymbol(ParserConstants.T_DNUMBER);
          }
        case 86: break;
        case 29: 
          { return createSymbol(ParserConstants.T_TILDA);
          }
        case 87: break;
        case 20: 
          { return createSymbol(ParserConstants.T_OR);
          }
        case 88: break;
        case 27: 
          { return createSymbol(ParserConstants.T_OPEN_PARENTHESE);
          }
        case 89: break;
        case 24: 
          { return createSymbol(ParserConstants.T_COMMA);
          }
        case 90: break;
        case 4: 
          { dump("FOUND T_VARIABLE");
    return createFullSymbol(ParserConstants.T_VARIABLE);
          }
        case 91: break;
        case 40: 
          { yypushback(yylength());
    popState();
    pushState(ST_IN_SCRIPTING);
          }
        case 92: break;
        case 68: 
          { pushState(ST_IN_SCRIPTING);
    yypushback(yylength()-1);
    return createSymbol(ParserConstants.T_CURLY_OPEN_WITH_DOLAR);
          }
        case 93: break;
        case 53: 
          { return createSymbol(ParserConstants.T_IS_NOT_EQUAL);
          }
        case 94: break;
        case 13: 
          { return createSymbol(ParserConstants.T_NOT);
          }
        case 95: break;
        case 70: 
          { dump("START TWIG SCRIPTING");
    yybegin(ST_IN_SCRIPTING);
          }
        case 96: break;
        case 57: 
          { return createSymbol(ParserConstants.T_SR);
          }
        case 97: break;
        case 78: 
          { return createSymbol(ParserConstants.T_ELSE);
          }
        case 98: break;
        case 54: 
          { return createSymbol(ParserConstants.T_IS_SMALLER_OR_EQUAL);
          }
        case 99: break;
        case 32: 
          { /* This is a temporary fix which is dependant on flex and it's implementation */
    if (!stack.isEmpty()) {
        popState();
    }
    return createSymbol(ParserConstants.T_CURLY_CLOSE);
          }
        case 100: break;
        case 69: 
          { yypushback(1);
	return createFullSymbol(ParserConstants.T_ENCAPSED_AND_WHITESPACE);
          }
        case 101: break;
        case 35: 
          { yybegin(ST_IN_SCRIPTING);
    return createSymbol(ParserConstants.T_QUATE);
          }
        case 102: break;
        case 59: 
          { return createSymbol(ParserConstants.T_DIV_EQUAL);
          }
        case 103: break;
        case 82: 
          { return createSymbol(ParserConstants.T_ENDFOR);
          }
        case 104: break;
        case 79: 
          { handleCommentStart();
          }
        case 105: break;
        case 36: 
          { yybegin(ST_IN_SCRIPTING);
    return createSymbol(ParserConstants.T_BACKQUATE);
          }
        case 106: break;
        case 81: 
          { return createSymbol(ParserConstants.T_ELSEIF);
          }
        case 107: break;
        case 47: 
          { return createSymbol(ParserConstants.T_IF);
          }
        case 108: break;
        case 61: 
          { return createSymbol(ParserConstants.T_AND_EQUAL);
          }
        case 109: break;
        case 85: 
          { handleVarComment();
    //return createFullSymbol(ParserConstants.T_VAR_COMMENT);
          }
        case 110: break;
        case 44: 
          { return createSymbol(ParserConstants.T_DEC);
          }
        case 111: break;
        case 6: 
          { dump("WHITESPACE");
          }
        case 112: break;
        case 7: 
          { return createSymbol(ParserConstants.T_DOLLAR);
          }
        case 113: break;
        case 48: 
          { return createSymbol(ParserConstants.T_LOGICAL_OR);
          }
        case 114: break;
        case 16: 
          { return createSymbol(ParserConstants.T_TIMES);
          }
        case 115: break;
        case 8: 
          { yybegin(ST_DOUBLE_QUOTES);
    return createSymbol(ParserConstants.T_QUATE);
          }
        case 116: break;
        case 55: 
          { return createSymbol(ParserConstants.T_SL);
          }
        case 117: break;
        case 83: 
          { return createSymbol(ParserConstants.T_EXTENDS);
          }
        case 118: break;
        case 74: 
          { return createSymbol(ParserConstants.T_USE);
          }
        case 119: break;
        case 58: 
          { return createSymbol(ParserConstants.T_MUL_EQUAL);
          }
        case 120: break;
        case 67: 
          { yypushback(1);
    return createFullSymbol(ParserConstants.T_ENCAPSED_AND_WHITESPACE);
          }
        case 121: break;
        case 23: 
          { return createSymbol(ParserConstants.T_NEKUDOTAIM);
          }
        case 122: break;
        case 3: 
          { dump("CREATING OBJECT OPERATOR IN SCRIPTING STATE");
    pushState(ST_LOOKING_FOR_PROPERTY);
    return createSymbol(ParserConstants.T_OBJECT_OPERATOR);
          }
        case 123: break;
        case 65: 
          { return createSymbol(ParserConstants.T_XOR_EQUAL);
          }
        case 124: break;
        case 19: 
          { return createSymbol(ParserConstants.T_REFERENCE);
          }
        case 125: break;
        case 77: 
          { dump("FOUND LOOKING FOR PROPERTY");
	yypushback(3);
	pushState(ST_LOOKING_FOR_PROPERTY);
	return createFullSymbol(ParserConstants.T_VARIABLE);
          }
        case 126: break;
        case 15: 
          { return createSymbol(ParserConstants.T_LGREATER);
          }
        case 127: break;
        case 39: 
          { dump("IN PROPERTY LOOKUP CREATE STRING");
    popState();
    return createFullSymbol(ParserConstants.T_STRING);
          }
        case 128: break;
        case 60: 
          { return createSymbol(ParserConstants.T_MOD_EQUAL);
          }
        case 129: break;
        case 11: 
          { return createSymbol(ParserConstants.T_PLUS);
          }
        case 130: break;
        case 66: 
          { dump("END TWIG SCRIPTING");
	if (Debug.debugLexer)
		System.out.println();
		
    yybegin(YYINITIAL);
    return createSymbol(ParserConstants.T_SEMICOLON);  /* implicit ';' at php-end tag */
          }
        case 131: break;
        case 22: 
          { return createSymbol(ParserConstants.T_SEMICOLON);
          }
        case 132: break;
        case 33: 
          { System.out.print(yytext());
          }
        case 133: break;
        case 37: 
          { yypushback(yylength());
    popState();
          }
        case 134: break;
        case 50: 
          { return createSymbol(ParserConstants.T_INC);
          }
        case 135: break;
        case 73: 
          { return createSymbol(ParserConstants.T_LOGICAL_AND);
          }
        case 136: break;
        case 31: 
          { return createSymbol(ParserConstants.T_AT);
          }
        case 137: break;
        case 25: 
          { return createSymbol(ParserConstants.T_OPEN_RECT);
          }
        case 138: break;
        case 49: 
          { return createSymbol(ParserConstants.T_AS);
          }
        case 139: break;
        case 2: 
          { return createFullSymbol(ParserConstants.T_LNUMBER);
          }
        case 140: break;
        case 63: 
          { return createSymbol(ParserConstants.T_OR_EQUAL);
          }
        case 141: break;
        case 14: 
          { return createSymbol(ParserConstants.T_RGREATER);
          }
        case 142: break;
        case 72: 
          { return createSymbol(ParserConstants.T_FOR);
          }
        case 143: break;
        case 41: 
          { popState();
    pushState(ST_IN_SCRIPTING);
    return createFullSymbol(ParserConstants.T_STRING_VARNAME);
          }
        case 144: break;
        case 46: 
          { return createFullSymbol(ParserConstants.T_CONSTANT_ENCAPSED_STRING);
          }
        case 145: break;
        case 38: 
          { dump("CREATING OBJECT OPERATOR IN LOOKING FOR PROPERTY STATE");
	return createSymbol(ParserConstants.T_OBJECT_OPERATOR);
          }
        case 146: break;
        case 76: 
          { return createSymbol(ParserConstants.T_SR_EQUAL);
          }
        case 147: break;
        case 21: 
          { return createSymbol(ParserConstants.T_KOVA);
          }
        case 148: break;
        case 43: 
          { return createSymbol(ParserConstants.T_CONCAT_EQUAL);
          }
        case 149: break;
        case 64: 
          { return createSymbol(ParserConstants.T_BOOLEAN_OR);
          }
        case 150: break;
        case 17: 
          { return createSymbol(ParserConstants.T_DIV);
          }
        case 151: break;
        case 28: 
          { return createSymbol(ParserConstants.T_CLOSE_PARENTHESE);
          }
        case 152: break;
        case 34: 
          { return createFullSymbol(ParserConstants.T_ENCAPSED_AND_WHITESPACE);
          }
        case 153: break;
        case 5: 
          { return createSymbol(ParserConstants.T_MINUS);
          }
        case 154: break;
        case 12: 
          { return createSymbol(ParserConstants.T_EQUAL);
          }
        case 155: break;
        case 9: 
          { yybegin(ST_BACKQUOTE);
    return createSymbol(ParserConstants.T_BACKQUATE);
          }
        case 156: break;
        case 62: 
          { return createSymbol(ParserConstants.T_BOOLEAN_AND);
          }
        case 157: break;
        case 71: 
          { return createSymbol(ParserConstants.T_LOGICAL_XOR);
          }
        case 158: break;
        case 84: 
          { return createSymbol(ParserConstants.T_INCLUDE);
          }
        case 159: break;
        case 56: 
          { return createSymbol(ParserConstants.T_IS_GREATER_OR_EQUAL);
          }
        case 160: break;
        case 1: 
          { // do nothing
          }
        case 161: break;
        case 10: 
          { pushState(ST_IN_SCRIPTING);
    return createSymbol(ParserConstants.T_CURLY_OPEN);
          }
        case 162: break;
        case 26: 
          { return createSymbol(ParserConstants.T_CLOSE_RECT);
          }
        case 163: break;
        case 45: 
          { return createSymbol(ParserConstants.T_MINUS_EQUAL);
          }
        case 164: break;
        case 52: 
          { return createSymbol(ParserConstants.T_IS_EQUAL);
          }
        case 165: break;
        case 75: 
          { return createSymbol(ParserConstants.T_SL_EQUAL);
          }
        case 166: break;
        case 30: 
          { return createSymbol(ParserConstants.T_QUESTION_MARK);
          }
        case 167: break;
        case 51: 
          { return createSymbol(ParserConstants.T_PLUS_EQUAL);
          }
        case 168: break;
        case 80: 
          { return createSymbol(ParserConstants.T_ENDIF);
          }
        case 169: break;
        case 18: 
          { return createSymbol(ParserConstants.T_PRECENT);
          }
        case 170: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {     return createSymbol(sym.EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java TwigAstLexer <inputfile>");
    }
    else {
      for (int i = 0; i < argv.length; i++) {
        TwigAstLexer scanner = null;
        try {
          scanner = new TwigAstLexer( new java.io.FileReader(argv[i]) );
          while ( !scanner.zzAtEOF ) scanner.next_token();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
