
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jan 05 17:47:03 CET 2012
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class ParserConstants {
  /* terminals */
  public static final int T_VARIABLE = 7;
  public static final int NUMBER = 5;
  public static final int T_RAW = 2;
  public static final int T_BLOCK_NAME = 10;
  public static final int T_ENCAPSED_AND_WHITESPACE = 8;
  public static final int EOF = 0;
  public static final int T_QUATE = 3;
  public static final int ID = 6;
  public static final int error = 1;
  public static final int T_CONSTANT_ENCAPSED_STRING = 9;
  public static final int T_BACKQUATE = 4;
}

