
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jan 06 23:27:41 CET 2012
//----------------------------------------------------

package com.dubture.twig.core.parser.ast;

/** CUP generated class containing symbol constants. */
public class ParserConstants {
  /* terminals */
  public static final int TWIG_VAR_OPEN = 5;
  public static final int TWIG_STMT_OPEN = 7;
  public static final int T_QUATE = 3;
  public static final int T_VARIABLE = 14;
  public static final int TWIG_VAR_CLOSE = 6;
  public static final int ID = 13;
  public static final int T_BLOCK_NAME = 17;
  public static final int EOF = 0;
  public static final int NUMBER = 12;
  public static final int T_RAW = 2;
  public static final int T_CLOSE_PARENTHESE = 10;
  public static final int T_DOT = 11;
  public static final int error = 1;
  public static final int T_ENCAPSED_AND_WHITESPACE = 15;
  public static final int T_CONSTANT_ENCAPSED_STRING = 16;
  public static final int TWIG_STMT_CLOSE = 8;
  public static final int T_BACKQUATE = 4;
  public static final int T_OPEN_PARENTHESE = 9;
}

