
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Jan 06 23:50:07 CET 2012
//----------------------------------------------------

package com.dubture.twig.core.parser.ast;

/** CUP generated class containing symbol constants. */
public class ParserConstants {
  /* terminals */
  public static final int TWIG_VAR_CLOSE = 3;
  public static final int T_VARIABLE = 8;
  public static final int T_BLOCK_NAME = 10;
  public static final int EOF = 0;
  public static final int TWIG_STMT_OPEN = 4;
  public static final int TWIG_VAR_OPEN = 2;
  public static final int error = 1;
  public static final int T_CLOSE_PARENTHESE = 7;
  public static final int T_CONSTANT_ENCAPSED_STRING = 9;
  public static final int T_OPEN_PARENTHESE = 6;
  public static final int TWIG_STMT_CLOSE = 5;
}

