
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jan 06 11:00:52 CET 2012
//----------------------------------------------------

package com.dubture.twig.core.parser.ast;

import java.util.LinkedList;
import java.util.List;
import com.dubture.twig.core.parser.ast.node.TwigModuleDeclaration;
import com.dubture.twig.core.parser.ast.node.BlockStatement;
import org.eclipse.dltk.ast.expressions.Expression;
import org.eclipse.dltk.ast.statements.Statement;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Fri Jan 06 11:00:52 CET 2012
  */
public class TwigAstParser extends AbstractAstParser {

  /** Default constructor. */
  public TwigAstParser() {super();}

  /** Constructor which sets the default scanner. */
  public TwigAstParser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public TwigAstParser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\013\000\002\002\003\000\002\002\004\000\002\002" +
    "\003\000\002\003\006\000\002\004\004\000\002\004\002" +
    "\000\002\005\003\000\002\006\003\000\002\006\003\000" +
    "\002\007\003\000\002\007\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\015\000\006\003\005\011\004\001\002\000\004\020" +
    "\011\001\002\000\004\002\uffff\001\002\000\004\002\010" +
    "\001\002\000\004\002\001\001\002\000\004\002\000\001" +
    "\002\000\010\012\ufffc\013\ufffc\015\ufffc\001\002\000\010" +
    "\012\013\013\016\015\015\001\002\000\004\002\ufffe\001" +
    "\002\000\010\012\ufffd\013\ufffd\015\ufffd\001\002\000\010" +
    "\012\ufffa\013\ufffa\015\ufffa\001\002\000\010\012\ufff9\013" +
    "\ufff9\015\ufff9\001\002\000\010\012\ufffb\013\ufffb\015\ufffb" +
    "\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\015\000\006\002\005\003\006\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\004\011\001\001\000\006\005" +
    "\013\006\016\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$TwigAstParser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$TwigAstParser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$TwigAstParser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 1;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    
    /* Change the method report_error so it will display the line and
       column of where the error occurred in the input as well as the
       reason for the error which is passed into the method in the
       String 'message'. */
    public void report_error(String message, Object info) {
   
        /* Create a StringBuffer called 'm' with the string 'Error' in it. */
        StringBuffer m = new StringBuffer("Error");
   
        /* Check if the information passed to the method is the same
           type as the type java_cup.runtime.Symbol. */
        if (info instanceof java_cup.runtime.Symbol) {
            /* Declare a java_cup.runtime.Symbol object 's' with the
               information in the object info that is being typecasted
               as a java_cup.runtime.Symbol object. */
            java_cup.runtime.Symbol s = ((java_cup.runtime.Symbol) info);
   
            /* Check if the line number in the input is greater or
               equal to zero. */
            if (s.left >= 0) {                
                /* Add to the end of the StringBuffer error message
                   the line number of the error in the input. */
                m.append(" in line "+(s.left+1));   
                /* Check if the column number in the input is greater
                   or equal to zero. */
                if (s.right >= 0)                    
                    /* Add to the end of the StringBuffer error message
                       the column number of the error in the input. */
                    m.append(", column "+(s.right+1));
            }
        }
   
        /* Add to the end of the StringBuffer error message created in
           this method the message that was passed into this method. */
        m.append(" : "+message);
   
        /* Print the contents of the StringBuffer 'm', which contains
           an error message, out on a line. */
        System.err.println(m + " tralala");
    }
   
    /* Change the method report_fatal_error so when it reports a fatal
       error it will display the line and column number of where the
       fatal error occurred in the input as well as the reason for the
       fatal error which is passed into the method in the object
       'message' and then exit.*/
    public void report_fatal_error(String message, Object info) {
        report_error(message, info);
       
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$TwigAstParser$actions {
  private final TwigAstParser parser;

  /** Constructor */
  CUP$TwigAstParser$actions(TwigAstParser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$TwigAstParser$do_action(
    int                        CUP$TwigAstParser$act_num,
    java_cup.runtime.lr_parser CUP$TwigAstParser$parser,
    java.util.Stack            CUP$TwigAstParser$stack,
    int                        CUP$TwigAstParser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$TwigAstParser$result;

      /* select the action based on the action number */
      switch (CUP$TwigAstParser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // term ::= T_VARIABLE 
            {
              String RESULT =null;
		int varleft = ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()).left;
		int varright = ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()).right;
		String var = (String)((java_cup.runtime.Symbol) CUP$TwigAstParser$stack.peek()).value;
		 RESULT = var; 
              CUP$TwigAstParser$result = parser.getSymbolFactory().newSymbol("term",5, ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()), RESULT);
            }
          return CUP$TwigAstParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // term ::= NUMBER 
            {
              String RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$TwigAstParser$stack.peek()).value;
		 RESULT = n; 
              CUP$TwigAstParser$result = parser.getSymbolFactory().newSymbol("term",5, ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()), RESULT);
            }
          return CUP$TwigAstParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // statement ::= NUMBER 
            {
              Object RESULT =null;
		int nleft = ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()).left;
		int nright = ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()).right;
		String n = (String)((java_cup.runtime.Symbol) CUP$TwigAstParser$stack.peek()).value;
		
        RESULT = n;
    
              CUP$TwigAstParser$result = parser.getSymbolFactory().newSymbol("statement",4, ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()), RESULT);
            }
          return CUP$TwigAstParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // statement ::= T_VARIABLE 
            {
              Object RESULT =null;
		int statementleft = ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()).left;
		int statementright = ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()).right;
		String statement = (String)((java_cup.runtime.Symbol) CUP$TwigAstParser$stack.peek()).value;
		 
        RESULT = statement; 
    
              CUP$TwigAstParser$result = parser.getSymbolFactory().newSymbol("statement",4, ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()), RESULT);
            }
          return CUP$TwigAstParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // inner_statement ::= statement 
            {
              Object RESULT =null;
		int statementleft = ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()).left;
		int statementright = ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()).right;
		Object statement = (Object)((java_cup.runtime.Symbol) CUP$TwigAstParser$stack.peek()).value;
		 
        RESULT = statement; 
    
              CUP$TwigAstParser$result = parser.getSymbolFactory().newSymbol("inner_statement",3, ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()), RESULT);
            }
          return CUP$TwigAstParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // inner_statement_list ::= 
            {
              List RESULT =null;
		 
        RESULT = new LinkedList(); 
    
              CUP$TwigAstParser$result = parser.getSymbolFactory().newSymbol("inner_statement_list",2, ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()), RESULT);
            }
          return CUP$TwigAstParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // inner_statement_list ::= inner_statement_list inner_statement 
            {
              List RESULT =null;
		int statementListleft = ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.elementAt(CUP$TwigAstParser$top-1)).left;
		int statementListright = ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.elementAt(CUP$TwigAstParser$top-1)).right;
		List statementList = (List)((java_cup.runtime.Symbol) CUP$TwigAstParser$stack.elementAt(CUP$TwigAstParser$top-1)).value;
		int statementleft = ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()).left;
		int statementright = ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()).right;
		Object statement = (Object)((java_cup.runtime.Symbol) CUP$TwigAstParser$stack.peek()).value;
		
        // Ignore null statements
        if(statement != null) {
            statementList.add(statement);
        }
        RESULT = statementList;
    
              CUP$TwigAstParser$result = parser.getSymbolFactory().newSymbol("inner_statement_list",2, ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.elementAt(CUP$TwigAstParser$top-1)), ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()), RESULT);
            }
          return CUP$TwigAstParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // block ::= TWIG_STMT_OPEN T_BLOCK_NAME inner_statement_list TWIG_STMT_CLOSE 
            {
              BlockStatement RESULT =null;
		int startleft = ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.elementAt(CUP$TwigAstParser$top-3)).left;
		int startright = ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.elementAt(CUP$TwigAstParser$top-3)).right;
		Object start = (Object)((java_cup.runtime.Symbol) CUP$TwigAstParser$stack.elementAt(CUP$TwigAstParser$top-3)).value;
		int nameleft = ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.elementAt(CUP$TwigAstParser$top-2)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.elementAt(CUP$TwigAstParser$top-2)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$TwigAstParser$stack.elementAt(CUP$TwigAstParser$top-2)).value;
		int innerleft = ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.elementAt(CUP$TwigAstParser$top-1)).left;
		int innerright = ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.elementAt(CUP$TwigAstParser$top-1)).right;
		List inner = (List)((java_cup.runtime.Symbol) CUP$TwigAstParser$stack.elementAt(CUP$TwigAstParser$top-1)).value;
		int endleft = ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()).left;
		int endright = ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()).right;
		Object end = (Object)((java_cup.runtime.Symbol) CUP$TwigAstParser$stack.peek()).value;
		
                    BlockStatement stmt = new BlockStatement(startleft, endright, name, inner);
                    RESULT = stmt;
                 
              CUP$TwigAstParser$result = parser.getSymbolFactory().newSymbol("block",1, ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.elementAt(CUP$TwigAstParser$top-3)), ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()), RESULT);
            }
          return CUP$TwigAstParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // module ::= error 
            {
              TwigModuleDeclaration RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()).right;
		Object e = (Object)((java_cup.runtime.Symbol) CUP$TwigAstParser$stack.peek()).value;
		 
                    System.err.println("error");
                    RESULT = null;
                 
              CUP$TwigAstParser$result = parser.getSymbolFactory().newSymbol("module",0, ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()), RESULT);
            }
          return CUP$TwigAstParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // $START ::= module EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.elementAt(CUP$TwigAstParser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.elementAt(CUP$TwigAstParser$top-1)).right;
		TwigModuleDeclaration start_val = (TwigModuleDeclaration)((java_cup.runtime.Symbol) CUP$TwigAstParser$stack.elementAt(CUP$TwigAstParser$top-1)).value;
		RESULT = start_val;
              CUP$TwigAstParser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.elementAt(CUP$TwigAstParser$top-1)), ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$TwigAstParser$parser.done_parsing();
          return CUP$TwigAstParser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // module ::= block 
            {
              TwigModuleDeclaration RESULT =null;
		int bleft = ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()).left;
		int bright = ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()).right;
		BlockStatement b = (BlockStatement)((java_cup.runtime.Symbol) CUP$TwigAstParser$stack.peek()).value;
		                 
                    TwigModuleDeclaration module = parser.getModuleDeclaration();
                    System.err.println("create module...");
                    RESULT = module;
                 
              CUP$TwigAstParser$result = parser.getSymbolFactory().newSymbol("module",0, ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()), ((java_cup.runtime.Symbol)CUP$TwigAstParser$stack.peek()), RESULT);
            }
          return CUP$TwigAstParser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

